### PR TITLE
[#2173] Add LocalDateTime binder

### PR DESCRIPTION
**Pull request by sant0s**

### CODE REVIEW

**Comment by asolntsev** [comment]
@sant0s Thank you for the PR!

**Comment by sant0s** [comment]
@asolntsev You're welcome. Any chance (Lighthouse) tickets 2170 to 2172 could be resolved?

**Comment by asolntsev** [comment]
@sant0s Sure they can be resolved. Feel free to prepare a pull requests for them!

**Comment by Fraserhardy** [comment]
@sant0s @asolntsev I'm fairly certain issue 2172 is actually linked to issue 1849 which we've now fixed in this pr: https://github.com/playframework/play1/pull/1246 
It actually causes functional tests to return 200 for any exception! Which is critical in my opinion and has been open for quite some time.

**Comment by sant0s** [comment]
@Fraserhardy @asolntsev I also find it critical, as it inhibits testing, therefore reducing coverage.

**Comment by asolntsev** [comment]
@sant0s @Fraserhardy I added my comment to PRs #1230, #1231 and #1246. Thank you for your commitment!

**Comment by sant0s** [comment]
> @sant0s @Fraserhardy I added my comment to PRs #1230, #1231 and #1246. Thank you for your commitment!

@asolntsev #1231 didn't go through although #1230 did (in Play! 1.5.2.). Could #1231 be included in the next Play! release?

**Pull request merged**
