### PR TITLE
[#1353, #1355] update python 3

### PR DESCRIPTION
**Pull request by xael-fry**
# Pull Request Checklist

* [x] Have you read [How to write the perfect pull request](https://github.com/blog/1943-how-to-write-the-perfect-pull-request)?
* [x] Have you read through the [contributor guidelines](https://www.playframework.com/contributing)?
* [x] Have you referenced any issues you're fixing using [commit message keywords](https://help.github.com/articles/closing-issues-using-keywords/)?
* [x] Have you updated the documentation?
* [x] Have you added tests for any changed functionality?

# Helpful things

## Fixes

Fixes #xxxx

## Purpose

What does this PR do?

## Background Context

Why did you take this approach?

## References

Are there any relevant issues / PRs / mailing lists discussions?

### CODE REVIEW

**Comment by tomparle** [comment]
Thanks @xael-fry for your help on this.
I thought that adding libs like "mechanize" or "html5lib" was only needed in Play python lib folder, but it seems that you needed to add them on system level. Maybe you'll also need to add the "six" lib if not already present.
In the latest windows build, it also seems that the missing lib is "win32pdh" : if you do not have time to add it, I will try that tomorrow.

**Comment by xael-fry** [comment]
@tomparle The problem seem to be with the kill subprocess, the current kill function doesn't work as expected on windows as play is still running in backgroud

**Comment by tomparle** [comment]
@xael-fry Thanks for the insight. I recall having played with some other ways to kill the subprocess when migrating to Python 3, but it was not necessary to change at that time.
By the way, did you try to add the lib "win32pdh" which is missing in the latest build ? This seems to have caused the latest build to fail.
If you do not have time, I'll try to find some time to setup a Windows environment.

**Comment by xael-fry** [comment]
@tomparle it is fix :)... Yes!!!

**Comment by tomparle** [comment]
Yiepeeee !
Congrats, @xael-fry !

**Comment by tazmaniax** [comment]
@xael-fry @tomparle nice one guys!!!!

**Pull request merged**
