### PR TITLE
[#1934] Allow non-static controllers methods

### PR DESCRIPTION
**Pull request by angryziber**
Allow writing of non-static controller methods in Play 1.x, like in Play 2.4.x.

Non-static methods have lots of benefits, including:
- easier to extend/override
- easier to mock
- easier to unit-test in general

Change is fully backwards-compatible, as I have written unit tests for ActionInvoker before changing the method to make sure Scala support works the same way as before.

### CODE REVIEW

**Comment by arnzel** [comment]
+1 

That would be a great feature !

**Comment by xael-fry** [comment]
Nice feature. Can you create an issue and add some example in **just-test-cases** sample project?
Thanks

**Comment by xael-fry** [comment]
Ticket created [lighthouse #1934](https://play.lighthouseapp.com/projects/57987-play-framework/tickets/1934-allow-non-static-controllers-methods).
Can you add an Example and update **documentation/manual/controllers.textile** ?

**Comment by Odilio** [comment]
Great!!

2015-04-15 9:34 GMT-03:00 Alexandre Chatiron <notifications@github.com>:

**Comment by angryziber** [comment]
Thanks for creating an issue!
As for examples - just remove static keywords and it will work.

Before updating the documentation, I think it would be nice to create a new instance of controller only once, and run all befores/afters on the same instance. Current implementation creates a new instance on invocation of every method, so it is sort of experimental.

**Comment by angryziber** [comment]
I have updated the docs and and changed code so that controller instance is created only once per request.

Unit tests cover that both old and new style works.

Is it good for a merge? :-)

**Comment by angryziber** [comment]
Guys, it would be nice to get some feedback.

Probably, I have overdone with docs and we may stick to static by default, just mentioning that non-static is possible?

**Comment by arnzel** [comment]
+1 for this feature

**Comment by xael-fry** [comment]
Merged and pushed in master, 1.3.x and 1.4.x
Thanks

**Pull request closed without merging**
