### PR TITLE
Upgrade hibernate

### PR DESCRIPTION
**Pull request by asolntsev**
See issue https://github.com/playframework/play1/issues/1113

This pull request is not finally ready yet. I am sharing it just for your early reviews (if anybody is interested). I will continue working on it.

### CODE REVIEW

**Comment by tazmaniax** [comment]
hi @asolntsev,

Does the patch file (https://github.com/playframework/play1/blob/master/framework/patches/hibernate-4.2.19-patch-play.patch.patch) still need to be applied to the new version of Hibernate?

cheers

**Comment by asolntsev** [comment]
@tazmaniax Thank you for the hint! Actually I don't know an answer. 
At least, everything works in my current project without this patch. 

Can you help me: do you know why this hack was needed?

**Comment by asolntsev** [comment]
@tazmaniax I tried this patch, and it helped.
Thank you a lot! You really helped me with this annoying hibernate issue.

P.S. There is still a question in the air: why this hack was needed? Why does Play framework use such hidden unobvious hacks?

**Comment by flybyray** [comment]
@asolntsev [The hibernate patch](https://github.com/playframework/play1/issues/1113#issuecomment-299637963) is part of the code base for a long time. Play! 1 started with hibernate from Version 3. There was a time when the hibernate3xxx.jar has been distrubuted as patched wihtout the patch source (that was really hidden).
Please read the [jpa.textile @ explicit-save (linked the initial one from c931cbd  on 1 Sep 2009)](https://github.com/playframework/play1/blob/c931cbd09b39bdba77aff8082e235b21e22421b3/documentation/manual/jpa.textile#explicit-save) 

Here just the essential hint of what was changed for Play!:

> So, that exactly what we’ve changed in play. All the perstistent objects extending the JPASupport/JPAModel, will not be automactically saved without an explicit call to the save() method. So you can effectively rewrite the previous code as 

Maybe it is a good time to enhence the JPA documentation to make an association to that patch (that is really missing for someone who wants to upgrade hibernate version).

**Comment by asolntsev** [comment]
@flybyray Thank you for clarification. I like the idea of maintaining object state manually and calling `save` explicitly. I just don't like that this implementation detail was so much hidden. It made me waste lot of time. :(

And I wonder: is it real that nobody but Play needs to disable dirty check in Hibernate? Probably there is a more common solution for this problem? 

P.S. I created a simpler solution: I renamed `hibernate-core-x.y.z.FINAL.jar` to `hibernate-core-x.y.z.PATCHED.jar`. I think it show very well that the jar has been modified.

**Comment by asolntsev** [comment]
@xael-fry @tazmaniax @flybyray Yihhaaaa!!! This day came! 
The build got green. The upgrade to hibernate5 is ready now. 

Can you review the changes and merge the pull request?

**Comment by flybyray** [comment]
From my point of view looking the github pull request diff it is ok:
diff: https://patch-diff.githubusercontent.com/raw/playframework/play1/pull/1114.diff
compare: https://github.com/playframework/play1/compare/master...codeborne:upgrade-hibernate

**But I have the feeling that something is wrong with github pull request comparison.**

Github shows me 38 Files changed. But if i check the pull request locally there are more changes, which are missing or filtered by github pull request api.
How I checked that?[ I did checkout/fetch the a pull request locally](https://help.github.com/articles/checking-out-pull-requests-locally/) as `refs/heads/pull1114`. For demonstration i added the codeborne repository too.
```sh
$ git config --get-regexp remote.*.url
remote.origin.url git@github.com:playframework/play1.git
remote.codeborne.url git@github.com:codeborne/play.git
$ git for-each-ref --sort=-committerdate refs/heads/
58c870efea9532b0e84edbb7828e578d374c999b commit	refs/heads/master
b128c17f0d34ef15dc3d94acbd83a0cdfef5feb6 commit	refs/heads/upgrade-hibernate
b128c17f0d34ef15dc3d94acbd83a0cdfef5feb6 commit	refs/heads/pull1114
$ git status
Auf Branch master
Ihr Branch ist auf dem selben Stand wie 'origin/master'.
$ git diff refs/heads/pull1114   --name-only | wc -l
110
```
The pull request has 110 files changed. Some file changes are less important, maybe github filtered them out. But those changes, changed/removed javadoc, reorganized import statements ...

Maybe it would be better to have a single commit pull request. Maybe github has some problems with multiple commits including hugh binaries. The patch is really big because of binaries https://github.com/playframework/play1/pull/1114.patch

I was somehow surprised that the hibernate patch does not need any modification at all for the upgrade from 4 to 5. Maybe I should check that in detail? Did you run the hibernate tests itself (yes some will be failing in local environment, round about 2 or 4 tests failed for hibernate 4)?

**Comment by asolntsev** [comment]
@flybyray I did `git rebase` meanwhile, squashing several commits into one. Now the PR has 5 commits (instead of former 15-20). Probably it also created a confusion.

**Comment by flybyray** [comment]
@asolntsev no is all ok, but maybe fix the line endings in `samples-and-tests/just-test-cases/test/SimpleJPATest.java` too with your pull request (windows line endings)

**Comment by asolntsev** [comment]
@flybyray done (removed file endings)

**Comment by asolntsev** [comment]
@xael-fry I cannot reproduce your problem with warnings. Which application can I use to reproduce it? Which application contains `Table "API_CONSTRAINTS"`?

**Comment by xael-fry** [comment]
@asolntsev It is in my project it is just a simple, I will try to extract it for testing

**Comment by xael-fry** [comment]
@asolntsev 
 I change my mind, as the problem (warning logs) I had,  doesn't seems to have impact on running behavior, I suggest we merged it, and prepare a 1.5.0 RC1, to have some return from users.

**Comment by asolntsev** [comment]
@xael-fry Thank you!
Merged. Executed all tests on my working project - everything is green. Ready for RC.

**Pull request merged**
