### PR TITLE
dependencies upgrade

### PR DESCRIPTION
**Pull request by dejan2609**
* bouncycastle: ('bcprov-jdk15on' and 'bcpkix-jdk15on'): 1.57 -->> 1.60
  * groovy: 2.4.11 -->> 2.4.15
  * joda-time: 2.9.9 -->> 2.10
  * JDBC connectors:
 	 ** mysql-connector-java: 5.1.41 -->> 5.1.46 (see notes and links below)
     ** postgresql: 9.0 -->> 42.2.4 (42.x line supports PostgreSQL 8.2 and higher: https://jdbc.postgresql.org/documentation/faq.html#versioning)

MySQL connector notes:
  * line 5.1.x: it seems that mysql-connector-java 5.1.x line supports MySQL server versions >= 5.1
      ** version 5.1.41 release notes (https://forums.mysql.com/read.php?3,655541) claim that version is 'suitable for use with many MySQL server versions, including 4.1, 5.0, 5.1, 5.4 and 5.5'
      ** version 5.1.46 release notes (https://forums.mysql.com/read.php?3,664948) fail to mention support for versions < 5.5 (presumably, this will encourage users to upgrade their MySQL server(s) to a more recent version). However, compatibility with archived MySQL server versions should be kept (highly likely/almost certainly).
  * line 8.0.x: supports only MySQL server versions >= 5.5 (according to release notes, that is)

Dozen of related links:
    * https://dev.mysql.com/downloads/connector/j/5.1.html
    * https://insidemysql.com/mysql-connectorj-5-1-41-has-been-released
    * https://dev.mysql.com/doc/relnotes/connector-j/5.1/en/news-5-1-41.html
    * https://forums.mysql.com/read.php?3,655541 MySQL Connector/J 5.1.41 has been released
    * https://insidemysql.com/mysql-connector-java-5-1-46
    * https://dev.mysql.com/doc/relnotes/connector-j/5.1/en/news-5-1-46.html
    * https://forums.mysql.com/read.php?3,664948 MySQL Connector/Java 5.1.46 GA has been released
    * https://dev.mysql.com/downloads/connector/j/8.0.html
    * https://insidemysql.com/connector-j-8-0-11-the-face-for-your-brand-new-document-oriented-database
    * https://insidemysql.com/mysql-connector-java-8-0-12
    * https://dev.mysql.com/doc/relnotes/connector-j/8.0/en/news-8-0-12.html

### CODE REVIEW

**Comment by dejan2609** [comment]
FYI @asolntsev, @xael-fry

**Comment by asolntsev** [comment]
@dejan2609 Thank you! merged.

**Comment by theo** [comment]
@xael-fry question - why do the mysql and postgres driver libs have to be pulled in explicitly by the framework? Shouldn't they be specified depending on the application use case?

Applications reserve the right to pull in their own driver and driver versions, no?

**Comment by asolntsev** [comment]
@theo Play framework provides these libraries out-of-the-box. This is ok in most cases.
And application **can override** them if needed. Just declare another version of these libraries in your application's `dependencies.yml`. 

The only thing you really cannot do is to **remove** some dependency - e.g. if you don't use MySql or Postres at all. But you can achieve it just by calling `play deps && rm -fr lib/mysql*.jar`

**Pull request merged**
