### PR TITLE
[#2179,#2180]:Fix some bugs.

### PR DESCRIPTION
**Pull request by moshoujingli**
Fix that the exclusion check not effects the path which in the exclusion list itself.
Fix sometimes change log config not work.

### CODE REVIEW

**Comment by asolntsev** [comment]
@xael-fry PR approved. Recommended to merge.

**Comment by moshoujingli** [comment]
seems another bug in my env.

**Comment by asolntsev** [comment]
@moshoujingli The build is failing. Can you explain why you changed class `Logger.java`?
In the failing test, your new code `Thread.currentThread().getContextClassLoader().getResource(log4jPath)` cannot find file `log4j.properties`.

Tough, the old code `Logger.class.getResource(log4jPath)` could find it: `jar:file:/Users/andrei/projects/play/framework/play-1.5.x-1.5.1-9-gc59fc318.jar!/log4j.properties`

**Comment by xael-fry** [comment]
Fix it in https://github.com/playframework/play1/pull/1379

**Pull request closed without merging**
