### PR TITLE
[#1900] Added patch to allow H2 DB's web interface to start on a configured port

### PR DESCRIPTION
**Pull request by gadkrumholz**
Our Play application needed to use port 8082 and we needed to access the H2 DB web interface.

We patched DBPlugin to read port configuration from a new application.conf variable called "db.h2.webport".

It will still default to port 8082 if "db.h2.webport" configuration option is not defined in application.conf

### CODE REVIEW

**Comment by xael-fry** [comment]
Could you created and issue on [lighthouse](http://play.lighthouseapp.com/projects/57987-play-framework/overview)?

**Comment by gadkrumholz** [comment]
xael-fry, It's been created here now: http://play.lighthouseapp.com/projects/57987-play-framework/tickets/1900-added-patch-to-allow-h2-dbs-web-interface-to-start-on-a-configured-port

**Comment by gadkrumholz** [comment]
@xael-fry I've merged the latest 1.3.x branch into this pull request.

Thanks

**Comment by xael-fry** [comment]
Problem with your PR is that you suppose that the DB using H2 is the default one. How will it work if it is on another db like : 
```
db.teacher.url=jdbc:h2:mem:teacher
db.teacher.driver=org.h2.Driver
db.teacher.h2.webport=8862
```

Could you update doc too?
Thanks

**Comment by gadkrumholz** [comment]
@xael-fry 

Part 1:
I don't think the problem is really a problem... the H2 web interface only needs to be spawned once. It has its own separate configuration file (outside of play framework) that lets it connect to any H2 database with a JDBC URL (you can see it in the attached screenshot).

screenshot from 2015-02-20 15 00 59

The PR added option of db.h2.webport is meant to be used as a global option and does not need a per-database setting.

Does this make sense?

Part 2:
I'd be more than happy to update the docs pending your input/response from Part 1.

Thanks!

**Comment by asolntsev** [comment]
@gadkrumholz Hi! Do you still need this PR? Can you rebase it on `master` branch?

**Comment by gadkrumholz** [comment]
I no longer work at the place that needed this PR and they have since moved away from Play framework anyway. This is no longer needed and can probably be closed/removed. Thanks.

**Comment by asolntsev** [comment]
@gadkrumholz ok, thank you

**Pull request closed without merging**
