### PR TITLE
hibernate 5.4 update

### PR DESCRIPTION
**Pull request by sbeigel**
Updated to Hibernate 5.4.0.Final with patch (unchanged) and some dependencies.

### CODE REVIEW

**Comment by sbeigel** [comment]
...4.5.1 just got released, so I immediately updated this PR :)

**Comment by tazmaniax** [comment]
@sbeigel I'm thinking you meant 5.4.1 :) Nice one, thx!

**Comment by sbeigel** [comment]
lol, you're absolutly right! I'll edit the comment ;)

**Comment by xael-fry** [comment]
Merge and pushed in master.
Thanks

**Comment by EddyVerbruggen** [comment]
@sbeigel Do you perhaps recall why `framework/lib/ehcache-2.10.6.jar` was added as part of this PR? Previous versions of Play1 didn't unclude the `ehcache-xxx.jar` at all, and it's causing build issues for us.

**Comment by sbeigel** [comment]
@EddyVerbruggen ehcache-core 2.6.11 was the previous dependency, it was updated with this PR

**Comment by EddyVerbruggen** [comment]
@sbeigel Yes, that one was [upgraded indeed](https://github.com/playframework/play1/pull/1290/files#diff-3798bd17f908dbc19f1edef19e8a1131L38) (thanks!), but also, [this one sneaked in](https://github.com/sbeigel/play1/blob/81b4fe6eb94a42176caea24bdd000fc0d20a2c7e/framework/lib/ehcache-2.10.6.jar) and wasn't included before (not a lower version).

**Comment by EddyVerbruggen** [comment]
I guess we'll remove that lib from our play/libs folder for the time being.

**Pull request merged**
