### PR TITLE
dep upgrade: groovy 2.5.3 to be usable with Java 11

### PR DESCRIPTION
**Pull request by sbeigel**
## Fixes

Fixes [2263](https://play.lighthouseapp.com/projects/57987-play-framework/tickets/2263-update-groovy-to-253-to-be-usable-with-java-11)

### CODE REVIEW

**Comment by tomparle** [comment]
Hi @sbeigel, thank you for this pull request ! 
It's a good think to start the work to support JDK11.
The Groovy upgrade is needed indeed. May I kindly suggest to also review other Play dependencies as well and update them if needed ?
First, I am thinking in particular of the javassist lib whose [latest release 3.24.GA](https://github.com/jboss-javassist/javassist/releases/tag/rel_3_24_0_ga) also brings jdk11 compatibility.

I would also add that with JDK 11, I get 3 of the following trace at startup :
`java.io.IOException: Connection reset by peer
	at java.base/sun.nio.ch.FileDispatcherImpl.read0(Native Method)
	at java.base/sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:39)
	at java.base/sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:276)
	at java.base/sun.nio.ch.IOUtil.read(IOUtil.java:233)
	at java.base/sun.nio.ch.IOUtil.read(IOUtil.java:223)
	at java.base/sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:358)
	at org.jboss.netty.channel.socket.nio.NioWorker.read(NioWorker.java:64)
	at org.jboss.netty.channel.socket.nio.AbstractNioWorker.process(AbstractNioWorker.java:108)
	at org.jboss.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:337)
	at org.jboss.netty.channel.socket.nio.AbstractNioWorker.run(AbstractNioWorker.java:89)
	at org.jboss.netty.channel.socket.nio.NioWorker.run(NioWorker.java:178)
	at org.jboss.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108)
	at org.jboss.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
`
While this does not seem to prevent my application to run, I guess it may be the opportunity to review this more thoroughly, and maybe upgrade to a more recent version of netty (current is netty-all-4.1.31.Final) and ses if it would fix this. This would require some import fixes in Play's code, I'll also help if needed. 
If anyone would have something to add for this upgrade, please comment !

**Comment by sbeigel** [comment]
Hi @tomparle,
the javassist seems to be straight forward, but the upgrade to netty 4 seems to be not so easy... Unfortunately, I've not the time right now to look any deeper into this...

**Comment by tomparle** [comment]
Thank you for your answer @sbeigel !
Could you at least tell me if you also get the same warning as me (java.io.IOException: Connection reset by peer) when launching an app ? So I'll know if I am the only one impacted by this !
Cheers

**Comment by sbeigel** [comment]
I created PR #1280 for the javassist update (3.24.0)

**Comment by sbeigel** [comment]
> Could you at least tell me if you also get the same warning as me (java.io.IOException: Connection reset by peer) when launching an app ? So I'll know if I am the only one impacted by this !

I tried a quite large app of mine using the this play version with JDK 11 (in play DEV and PROD mode) but I don't see this warning...

**Comment by tomparle** [comment]
Thanks for the info, I think I will do a separated PR for Netty's migration.
I will do additional tests but it seems to work properly so far with JDK11 !

**Comment by tomparle** [comment]
Indeed, thanks for the information @tazmaniax ! Let's upgrade once 5.4 final is released, "within the next weeks" as stated in the website.

**Pull request merged**
