### PR TITLE
Bugfix/1430 do not get unused value

### LINKED ISSUE #1430: NullPointer in JPABase.cascadeOrphans() caused by unused lines
### Operating System (Ubuntu 15.10 / MacOS 10.10 / Windows 10)

Windows 10

### JDK (Oracle 1.8.0_72, OpenJDK 1.8.x, Azul Zing)

java version "1.8.0_333"

### Expected Behavior

Please describe the expected behavior of the issue, starting from the first action.

1. attempt to delete entity
2. JPABase._delete() is called
3. _delete() calls saveAndCascade()
4. saveAndCascade() calls cascadeOrphans()
5. entity is deleted

### Actual Behavior

1. attempt to delete entity
2. JPABase._delete() is called
3. _delete() calls saveAndCascade()
4. saveAndCascade() calls cascadeOrphans() -> throws NullPointer
5 entity is not deleted; all changes are rolled back as they should

### Findings

This is the code of the method which throws the error. 
````
private void cascadeOrphans(JPABase base, PersistentCollection persistentCollection, boolean willBeSaved) {
        String dbName = JPA.getDBName(this.getClass());

        SessionImpl session = ((SessionImpl) JPA.em(dbName).getDelegate());
        PersistenceContext pc = session.getPersistenceContext();
        CollectionEntry ce = pc.getCollectionEntry(persistentCollection);

        if (ce != null) {
            CollectionPersister cp = ce.getLoadedPersister();
            if (cp != null) {
                Type ct = cp.getElementType();
                if (ct instanceof EntityType) {
                    EntityEntry entry = pc.getEntry(base);
                    String entityName = entry.getEntityName(); // <- Exception thrown here
                    entityName = ((EntityType) ct).getAssociatedEntityName(session.getFactory());
                    if (ce.getSnapshot() != null) {
                        Collection orphans = ce.getOrphans(entityName, persistentCollection);
                        for (Object o : orphans) {
                            saveAndCascadeIfJPABase(o, willBeSaved);
                        }
                    }
                }
            }
        }
    }
````
The reason for these 3 lines escapes me:
   ```
   EntityEntry entry = pc.getEntry(base);
   String entityName = entry.getEntityName(); // <- Exception thrown here
   entityName = ((EntityType) ct).getAssociatedEntityName(session.getFactory());
   ```
      
`entityName` is initialized with a value that is immediatly overwritten in the next line. Could this not be rewritten as: 
 ```` 
  String  entityName = ((EntityType) ct).getAssociatedEntityName(session.getFactory());
 ````

Has someone else encountered this before?

### PR DESCRIPTION
**Pull request by aleksandy**
Some cleanup and fix #1430

### CODE REVIEW

**Review by asolntsev — APPROVED** [review]
@xael-fry LTGT. Recommended to merge.

**Comment by straycat264** [comment]
I notice you've tidied up the section of code which started:
`                        } else if (value instanceof PersistentCollection) {
                            PersistentCollection col = (PersistentCollection) value;
                            if (((PersistentCollection) value).wasInitialized()) {
`

Then proceeded to cascade the changes whether or not the collection was initialised. 
Your tidy-up consists of dispensing with the wasInitialized() check - presumably because it was seemingly redundant.

My question: we've observed that this code causes saveOrCascade to load collections that cannot have had any modifications (as they're not currently loaded) before saving - which has led to performance issues. Is there a good reason for this behaviour? I assume so, but it would be good to know what that reason is.

**Comment by aleksandy** [comment]
@straycat264, my changes didn't change code behaviour. It wasn't the goal of this PR.

The code in the if and else branches was the same, except that the PersistenceCollection in the if branch was passed through a cast of `value`, and the else used a separate variable `col` obtained by the same casting of the `value`. 

In my opinion, your question should be moved to separate ticket. Perhaps here should use the approach used to processing PersistenceMap and do nothing if the collection is not initialized.

**Review by xael-fry — APPROVED** [review]

**Comment by xael-fry** [comment]
Merge in master
Thanks @aleksandy

**Comment by JohannesBeranek** [comment]
@aleksandy @xael-fry 
```
                            if (((PersistentCollection) value).wasInitialized()) {
```
This line was removed in this commit - why?

**Comment by asolntsev** [comment]
@JohannesBeranek I don't remember the details, but I believe the resulting code is effectively the same. I think it was a refactoring suggested by IDEA: it removed duplicated/unneeded line, thus leading to a shorter code that does the same job.

**Pull request merged**
