### PR TITLE
Fix deadlock in data parser

### PR DESCRIPTION
**Pull request by asolntsev**
Original problem description: https://play.lighthouseapp.com/projects/57987-play-framework/tickets/1962-getting-static-initialization-deadlock-in-class-dataparser

### CODE REVIEW

**Comment by asolntsev** [comment]
Anybody? This could be merged to 1.3.x

**Comment by xael-fry** [comment]
Could you create an issue to described the problem?
Thanks

**Comment by asolntsev** [comment]
@xael-fry Hi, link to the issue was added in the very first comment: https://play.lighthouseapp.com/projects/57987-play-framework/tickets/1962-getting-static-initialization-deadlock-in-class-dataparser

**Comment by xael-fry** [comment]
Sorry I miss it.

**Comment by xael-fry** [comment]
Merged and pushed in master, 1.3.x and 1.4.x.
Thanks

**Pull request merged**
