### PR TITLE
add hibernate-ehcache jar to be able to use ehcach as second level cache

### PR DESCRIPTION
**Pull request by scesbron**
With play 1.2.x it was possible to use ehcache as hibernate second level cache. With play 1.4.1 this is not possible because there is a jar missing.

This is explained on that blog post : http://web.archive.org/web/20130117102553/http://www.javacraft.org/2012/03/migrate-to-hibernate-4-ehcache.html

With the `hibernate-ehcache jar` file it is possible to use ehcache as a second level cache by defining this entry in the `application.conf` file :

    hibernate.cache.use_second_level_cache=true
    hibernate.cache.use_query_cache=true
    hibernate.cache.region.factory_class=org.hibernate.cache.ehcache.EhCacheRegionFactory

### CODE REVIEW

**Comment by xael-fry** [comment]
Merged and pushed in master 1.3.x and 1.4.x.
Thanks

**Comment by dabeeeenster** [comment]
I get the following error in 1.4.4 with a new application and the three lines added to ```application.conf```
```
hibernate.cache.use_second_level_cache=true
hibernate.cache.use_query_cache=true
hibernate.cache.region.factory_class=org.hibernate.cache.ehcache.EhCacheRegionFactory
```

```
Oops: PersistenceException
Unexpected error : Unexpected Error, caused by exception PersistenceException: Unable to build EntityManagerFactory

play.exceptions.UnexpectedException: Unexpected Error
	at play.Play.start(Play.java:571)
	at play.Play.detectChanges(Play.java:659)
	at play.Invoker$Invocation.init(Invoker.java:209)
	at Invocation.HTTP Request(Play!)
Caused by: javax.persistence.PersistenceException: Unable to build EntityManagerFactory
	at org.hibernate.ejb.Ejb3Configuration.buildEntityManagerFactory(Ejb3Configuration.java:925)
	at org.hibernate.ejb.Ejb3Configuration.buildEntityManagerFactory(Ejb3Configuration.java:900)
	at play.db.jpa.JPAPlugin.onApplicationStart(JPAPlugin.java:198)
	at play.plugins.PluginCollection.onApplicationStart(PluginCollection.java:616)
	at play.Play.start(Play.java:541)
	... 3 more
Caused by: org.hibernate.service.spi.ServiceException: Unable to create requested service [org.hibernate.engine.spi.CacheImplementor]
	at org.hibernate.service.internal.AbstractServiceRegistryImpl.createService(AbstractServiceRegistryImpl.java:211)
	at org.hibernate.service.internal.AbstractServiceRegistryImpl.initializeService(AbstractServiceRegistryImpl.java:175)
	at org.hibernate.service.internal.AbstractServiceRegistryImpl.getService(AbstractServiceRegistryImpl.java:156)
	at org.hibernate.internal.SessionFactoryImpl.<init>(SessionFactoryImpl.java:267)
	at org.hibernate.cfg.Configuration.buildSessionFactory(Configuration.java:1799)
	at org.hibernate.ejb.EntityManagerFactoryImpl.<init>(EntityManagerFactoryImpl.java:96)
	at org.hibernate.ejb.Ejb3Configuration.buildEntityManagerFactory(Ejb3Configuration.java:918)
	... 7 more
Caused by: org.hibernate.cache.CacheException: net.sf.ehcache.CacheException: Another unnamed CacheManager already exists in the same VM. Please provide unique names for each CacheManager in the config or do one of following:
1. Use one of the CacheManager.create() static factory methods to reuse same CacheManager with same name or create one if necessary
2. Shutdown the earlier cacheManager before creating new one with same name.
The source of the existing CacheManager is: DefaultConfigurationSource [ ehcache.xml or ehcache-failsafe.xml ]
	at org.hibernate.cache.ehcache.EhCacheRegionFactory.start(EhCacheRegionFactory.java:110)
	at org.hibernate.internal.CacheImpl.<init>(CacheImpl.java:70)
	at org.hibernate.engine.spi.CacheInitiator.initiateService(CacheInitiator.java:40)
	at org.hibernate.engine.spi.CacheInitiator.initiateService(CacheInitiator.java:35)
	at org.hibernate.service.internal.SessionFactoryServiceRegistryImpl.initiateService(SessionFactoryServiceRegistryImpl.java:91)
	at org.hibernate.service.internal.AbstractServiceRegistryImpl.createService(AbstractServiceRegistryImpl.java:201)
	... 13 more
```

**Comment by EddyVerbruggen** [comment]
For anyone encountering the same issue as @dabeeeenster, this was due to a Hibernate upgrade; you now need to use

```
hibernate.cache.region.factory_class=org.hibernate.cache.ehcache.SingletonEhCacheRegionFactory
```

**Comment by dabeeeenster** [comment]
Is anyone able to get this working? I assume specific models need annotating? I've tried some annotations, enabled SQL logging, but the cache doesnt appear to be being used?

**Comment by EddyVerbruggen** [comment]
@dabeeeenster So you see the caches, but not the cache hits in the statistics? Stats are off by default, so you could add a config like this in `/conf/ehcache.xml` to override the defaults (mind the `statistics="true"`):

```xml
<ehcache xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:noNamespaceSchemaLocation="http://www.ehcache.org/ehcache.xsd" updateCheck="false">

  <!-- the default cache (blueprint) is 10k items big and caches stuff for 24 hours -->
  <defaultCache
      maxElementsInMemory="10000"
      statistics="true"
      timeToIdleSeconds="86400"
      timeToLiveSeconds="86400"
      overflowToDisk="false"
      diskPersistent="false"
      memoryStoreEvictionPolicy="LRU"/>
</ehcache>
```

**Comment by dabeeeenster** [comment]
OK - thats showing for me now - thanks

**Pull request merged**
