### PR TITLE
[#2007] Fix JPA classloader issues by hooking up Play's classloader

### PR DESCRIPTION
**Pull request by sbeigel**
The PR #767 tried to fix classloading issues w/ Hibernate, but using a precompiled app, this fix sill fails for a custom a NamingStrategy (and maybe other configs as well).
In the "precompile" step, Play sets the global classloader, so we do this (temporarily) for the JPA configuration as well.

### CODE REVIEW

**Comment by sbeigel** [comment]
The corresponding Lighthouse ticket is:
https://play.lighthouseapp.com/projects/57987-play-framework/tickets/2007

**Comment by sbeigel** [comment]
Re: "All checks have failed" -- the failing check/test doesn't seem to be caused by this PR?! Can someone please check this?

**Comment by sbeigel** [comment]
Hi Alexandre,
what's the status on this? We really need this feature for our (pre-compiled) deployments in production and it would be great to have this officially integrated! :)

**Comment by xael-fry** [comment]
Hi I want to integrate [your test](https://github.com/sbeigel/play-jpa-classloader-test) in the test to avoid further regression on this point, I expect to merge it this week.
Thanks

**Comment by xael-fry** [comment]
Merge and pushed in 1.3.x and 1.4.x
Thanks

**Pull request merged**
