### PR TITLE
Play scripts upgrade to Python 3

### PR DESCRIPTION
**Pull request by tomparle**
Upgrade all Play commands to python 3 (they were originally written in python 2).

## Purpose
This allow to keep Play 1 up-to-date with the current status of Python, whose version 2 is now longer maintained since January 1st, 2020.
This also allows to use Play in modern environments without Python 2 support, like Heroku current stack.

## Fixes
fixes https://github.com/playframework/play1/issues/1353

## Notes
I helped the migration with `futurize` but there was still quite some work to do manually.
I tested most commands and a successful build to Heroku-20 stack as well (which only supports python 3).

## Migration notes
This is a **breaking change**. This PR removes Python 2 support and requires now Python 3.

You may want to remove some print "hello" lines in some modules of your project that uses Play. The syntax causes an error in Python 3, and those lines are just sample code from the module template. They can be removed safely.
If you have custom-made modules with python scripts, you should migrate them manually to Python 3 (see some hints here : https://docs.python.org/3/howto/pyporting.html)

### CODE REVIEW

**Comment by xael-fry** [comment]
The python exec has not been updated (/python), Do we really need to keep it ? I thinking about removing it ?
What do you think ?
@tomparle @asolntsev @tazmaniax ?

**Comment by asolntsev** [comment]
> The python exec has not been updated (/python), Do we really need to keep it ? I thinking about removing it ? What do you think ? @tomparle @asolntsev @tazmaniax ?

I personally haven't used `/python` for a long time, but how will work users who used to `play foo` commands?

**Comment by xael-fry** [comment]
the wrapper is only for windows user, as it is the python.exe. So for windows user they will need to have it on their computer same for linux. or am I missing something ?

**Comment by asolntsev** [comment]
@xael-fry Ah Windows... Then we can drop it. Who cares about Windows users. :)

**Comment by tazmaniax** [comment]
Ah ok, I was confused about what you were referring to. As long as I can still call Play commands on MacOS and Linux then I'm good 😄

**Review by xael-fry — APPROVED** [review]

**Comment by tomparle** [comment]
Sorry for the late answer and thank you for the merge !
Indeed, the /python folder does not seem mandatory, but since I do not use Windows I'm not sure 100%.
Thanks for all the feedback.

**Comment by aleksandy** [comment]
Removing the /python folder will make play! useless out of the box in a Windows environment if the python is not installed. In my opinion, it is very bad for newbies if the getting started tips will fail because of lack of python.

**Comment by xael-fry** [comment]
@tomparle can you rebase this pr to master ?

**Comment by tomparle** [comment]
@xael-fry I spent quite some time to rebase properly (and fix my previous rebase mistakes), upgrade some recent changes to python 3 syntax, and fix some python libs which I did not setup properly due to some confusion with python system libs.

Finally the merge and the tests seems ok, except for the windows environment test suite which does not terminate. I do not use Windows for developing and does not know what's causing these tests to be suspend so some help could be useful.
Anyway I do not think this should be blocking for this merge.

**Comment by Alexandermjos** [comment]
Has anyone tried this on Windows? I get "ModuleNotFoundError: No module named 'win32pdh'" when using python 3.9.1 on Windows. 
"include win32pdh" works fine in python 2.7.8 included in Play 1.5.2

**Comment by rakix** [comment]
$ pip install pypiwin32

works fine Play 1.7 with Windows

**Comment by Alexandermjos** [comment]
Thank you 👍 
Is this considered common knowledge or something to consider putting into the documentation?

**Pull request merged**
