### PR TITLE
[#2075] dozen of dependencies are upgraded

### PR DESCRIPTION
**Pull request by dejan2609**
**Related ticket:**
- [Upgrade dozen of dependencies](https://play.lighthouseapp.com/projects/57987-play-framework/tickets/2075)

### CODE REVIEW

**Comment by asolntsev** [comment]
@dejan2609 Thank you, PR has been merged! The build is green.

**Comment by xael-fry** [comment]
@dejan2609 WTF is this commit comment?

**Comment by dejan2609** [comment]
@xael-fry My bad, commit message is inadequate... it should be something like this: https://github.com/playframework/play1/pull/971/commits/6b5a5a485cd7789f8bb6a6200f17ec010faf3dcd

Since initial commit is merged I can create new PR with in-detailed commit message .... sound ok with you ?

**Comment by xael-fry** [comment]
As I said : I Revert this commit in 1.4.x, update commit with details of modification and merged it again
. So you have nothing to do
Thanks

**Pull request merged**
