### PR TITLE
Libs: remove dependency on commons-collections

### PR DESCRIPTION
**Pull request by dp-ny**
There's also a vulnerability in commons-collections: "Apache Commons Collections contains a flaw in the InvokerTransformer class. This issue is triggered when handling Java code, which may invoke unsafe unserialize calls. This may allow a remote attacker to execute arbitrary code."

Although this flow isn't used, we should probably just stick to Java's default collections package when it's possible.

### CODE REVIEW

**Comment by dcpomeroy** [comment]
Looks like the tests are failing for unrelated reasons? java.lang.RuntimeException: java.util.concurrent.ExecutionException: java.net.ConnectException: connection timed out: /74.125.239.48:80

**Comment by asolntsev** [comment]
@dp-ny  Thank you for the pull request! Merging it.
The test failure is not related, it's just flaky test.

**Comment by asolntsev** [comment]
@dp-ny Merged PR to **master** and **1.4.x**

**Comment by xael-fry** [comment]
[Lighthouse #2057](https://play.lighthouseapp.com/projects/57987-play-framework/tickets/2057)

**Pull request merged**
