### PR TITLE
Java 11 (JDT update)

### PR DESCRIPTION
**Pull request by sbeigel**
Get ready for Java 11: JDT updated, option for Java source version 11 added

### CODE REVIEW

**Comment by sbeigel** [comment]
Ah, I'm afraid it's not that simple :) I think we have to update ASM to version 7.0 and to (re-)patch javaflow to make this work...

**Comment by tomparle** [comment]
Thank you for the contribution Sebastian !
Indeed, the latest version of asm offers better support for the JDK 11, with some welcomed fixes, so it's a good thing to have upgraded it too !

**Comment by sbeigel** [comment]
It's all green for me now, Java 11 source ist (pre-)compiled successfully, my web apps do work. I think together with my other PRs (mainly the hibernate 5.4 update) we should be ready for Java 11 :)

I'd appreciate if you could test a little bit as well and if it's all good, merge this stuff so we can all move to Java 11 ;)

**Comment by sbeigel** [comment]
To avoid conflicts, I rebased on master after the hibernate 5.4 changes got merged.

**Comment by xael-fry** [comment]
Merged and pushed in master
Thanks all @sbeigel @asolntsev ...

**Pull request merged**
