### PR TITLE
* fix(router): make some improvement in router 

### PR DESCRIPTION
**Pull request by Notalifeform**
Hi @xael-fry  - your PR looks fine; I added a selenium test to make sure there is an automated test. If you agree you can merge it.

### CODE REVIEW

**Comment by xael-fry** [comment]
Ok thank I will have a look, I had one too, but seems like i forget to put it in the commit ;)

**Comment by Notalifeform** [comment]
Hi @xael-fry, I added support for diacritics fro keys back into jsaction - it was broken due to the fix. I think the reason the code was not escaping, was to support it..

**Comment by xael-fry** [comment]
Merged in PR #859 .
Close it

**Comment by xael-fry** [comment]
Thanks

**Pull request closed without merging**
