### PR TITLE
Updated dependencies

### PR DESCRIPTION
**Pull request by tazmaniax**
Updated dependencies. All tests pass.

### CODE REVIEW

**Comment by tazmaniax** [comment]
@xael-fry FYI, thanks!

**Comment by tomparle** [comment]
Thanks for the deps update @tazmaniax !

**Comment by tazmaniax** [comment]
I've updated the dependencies as of today. All test pass.

**Comment by Alexandermjos** [comment]
Any ETA on release 1.8.0?

**Review by xael-fry — APPROVED** [review]

**Pull request merged**
