### PR TITLE
[#1403] 🐛 Fix Groovy compilation unit that tries to write in applicat…

### LINKED ISSUE #1403: Temporary class of Groovy template is output directly under application dir
### Play Version (1.5.x / etc)

1.7.0

### Operating System (Ubuntu 15.10 / MacOS 10.10 / Windows 10)

Debian GNU/Linux Bullseye/Ubuntu 20.04.4 LTS

### JDK (Oracle 1.8.0_72, OpenJDK 1.8.x, Azul Zing)

openjdk version "11.0.13" 2021-10-19
OpenJDK Runtime Environment (build 11.0.13+8-post-Debian-1deb11u1)
OpenJDK 64-Bit Server VM (build 11.0.13+8-post-Debian-1deb11u1, mixed mode, sharing)

### Expected Behavior

This is a followup on #1354 as I am not able to reopen this issue.
The same problem is still present in Play version 1.7.0 and prevent from using properly this version in a production deployment context where the JVM does not have write access to the root of the application.

Feel free to reopen #1354 and close this ticket.

### PR DESCRIPTION
**Pull request by holajsh**
Fix Groovy compilation unit that tries to write in application root folder

* Restore the old reflection code that completely replace the OUTPUT phase of Groovy compilation unit
* Fix the compilation exception handling that was producing cast error as not checking properly exception type

## Fixes

Fixes #1403

### CODE REVIEW

**Comment by tazmaniax** [comment]
@holajsh here was the [previous pull request #1368](https://github.com/playframework/play1/pull/1368) to fix this that was some how lost. Note the [comment](https://github.com/playframework/play1/pull/1368/files#diff-4af7248e1ba51b6a2050828be47026a82b5eb166baad4fde6959da135f0d4632R146-R150) that was included in the previous fix - probably worth bring in that whole change as it was.

**Comment by holajsh** [comment]
@tazmaniax ok, I have added the comment again in my PR, thx. Hope indeed it won't be lost again ;)

**Comment by tomparle** [comment]
> @holajsh here was the [previous pull request #1368](https://github.com/playframework/play1/pull/1368) to fix this that was some how lost. Note the [comment](https://github.com/playframework/play1/pull/1368/files#diff-4af7248e1ba51b6a2050828be47026a82b5eb166baad4fde6959da135f0d4632R146-R150) that was included in the previous fix - probably worth bringing in that whole change as it was. It's bit disconcerting that this previous PR was lost.

@tazmaniax my bad, although I tried my best I think I'm responsible for having messed this code when I rebased the Python 3 PR with master, because I got confused with what was new or not, since it was a revert to a previous code. Sorry and thank you for having detected and fixed this !

**Comment by tazmaniax** [comment]
@tomparle ah that's good to know where the regression might have come from, thanks for the heads up. So do you think this was the only regression or could there be others?

**Comment by tazmaniax** [comment]
@tomparle ok great!

**Pull request merged**
