### PR TITLE
Lighthouse#2273: Stop Fixtures attempting to set static (Map) fields

### PR DESCRIPTION
**Pull request by tazmaniax**
## Fixes
[Lighthouse #2273](https://play.lighthouseapp.com/projects/57987-play-framework/tickets/2273-fixtures-incorrectly-attempts-to-set-static-map-fields)

## Purpose
Stops Fixtures attempting to set static (Map) fields

## Background Context
Fixtures probably shouldn't be setting static fields

### CODE REVIEW

**Comment by tazmaniax** [comment]
@asolntsev not something I've done before but how hard can it be :) I'll be back...

**Comment by tazmaniax** [comment]
@asolntsev @xael-fry I've run into a class loading issue with my unit test, any idea?

```
java.lang.RuntimeException: Class models.ClassWithStaticMap was not found [type=models.ClassWithStaticMap,id=instanceA]
	at play.test.Fixtures.loadModels(Fixtures.java:294)
	at play.test.FixturesTest.testStaticMap(FixturesTest.java:57)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:538)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:760)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:460)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:206)
Caused by: java.lang.ClassNotFoundException: models.ClassWithStaticMap
	at java.base/java.lang.ClassLoader.findClass(ClassLoader.java:709)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:563)
	at play.classloading.ApplicationClassloader.loadClass(ApplicationClassloader.java:99)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:496)
	at play.test.Fixtures.loadModels(Fixtures.java:259)
	... 28 more
```

**Comment by tazmaniax** [comment]
@asolntsev thanks. I was hoping the Play classloader, with the way I'd configured it would have added the test folder as a classpath endpoint so the relative path of "models" would have been picked up but alas no. As it turns out when I did what you suggested Play prefixed the fully qualified class name with "models." so I got another class loading exception...
```
Caused by: java.lang.ClassNotFoundException: models.play.test.models.ClassWithStaticMap
	at java.base/java.lang.ClassLoader.findClass(ClassLoader.java:709)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:563)
	at play.classloading.ApplicationClassloader.loadClass(ApplicationClassloader.java:99)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:496)
	at play.test.Fixtures.loadModels(Fixtures.java:259)
	... 28 more
```
Anyway I got it working after jumping through some mocking hoops with application classes and plugins. Let me know if there was a better way and also if my unit test is valid, thx! Otherwise hopefully this can be accepted.

**Comment by asolntsev** [comment]
@tazmaniax Yes, it's a bad thing that Play adds prefix `models.` silently. 
I would recommend to just move class `play.test.models.ClassWithStaticMap` to package `models`. Them you don't need all these tricks with classloading. KISS, my friend :)

**Comment by tazmaniax** [comment]
@asolntsev ah that's a much better idea. My first impulse was to keep all of the test assets as close together as possible so it was easier to reason about and there was no prior example of the models package being used but I totally agree it's a better solution than my class loading magic :)

**Comment by tazmaniax** [comment]
@asolntsev is this good to go?

**Comment by asolntsev** [comment]
@tazmaniax @xael-fry PR is good. Recommended to merge.

**Comment by tazmaniax** [comment]
@xael-fry could you merge this? Once this is merged I'm going to build the head of master. thx

**Comment by tazmaniax** [comment]
@asolntsev @xael-fry can this be merged?

**Comment by asolntsev** [comment]
@tazmaniax I squashed 9 commits and merged to master branch. Thank you for the contribution!

**Comment by tazmaniax** [comment]
@asolntsev thx!

**Pull request merged**
