### PR TITLE
[#1669] Fix Seemingly random ClassNotFoundException on first request 

### PR DESCRIPTION
**Pull request by flybyray**
https://play.lighthouseapp.com/projects/57987/tickets/1669-seemingly-random-classnotfoundexception-on-first-request

### CODE REVIEW

**Comment by flybyray** [comment]
found a bug in this pull request, I will do apply a fix tomorrow (it is to late today)

**Comment by sbeigel** [comment]
Hi, I'm a little bit annoyed by these exceptions on startup in prod mode as well. What's the status on this problem/PR?
@flybyray: Could you rebase on the 1.3.x head? So other can check this out? And it would be great to not change ("mess up" :) the imports but just add the ones you're using ;)

**Comment by asolntsev** [comment]
@flybyray Sorry for the long delay. Now I started analysing your pull request. 
Can you explain **shortly**, how exactly it fixes the initial problem with ClassNotFoundException?

The initial problem was caused by the fast the Play code adds an unknown class to the global list, and removes it after some time. As I see, this buggie code still exists in your pull request. Am I right or not?

**Comment by flybyray** [comment]
several changes merged already. maybe not relevant anymore.

**Comment by asolntsev** [comment]
@flybyray No, I believe the issue is still relevant. 
I am pretty sure that no one of merge changes fixed the issue.

**Pull request closed without merging**
