### PR TITLE
fix for issue mentioned in issue 1113 comment 289165754

### PR DESCRIPTION
**Pull request by flybyray**
see https://github.com/playframework/play1/issues/1113#issuecomment-289165754

this is for 1.3.x branch

### CODE REVIEW

**Comment by asolntsev** [comment]
@flybyray Are you sure that `MANUAL` is better than `AUTO`? Why?
I am not sure at all.

Actually I solved the mentioned issue by patching hibernate-core.jar with [The Patch](https://github.com/playframework/play1/blob/a1f35221d63414e704d2b92200264d0738314c77/framework/patches/hibernate-4.2.19-patch-play.patch.patch) which disbled Hibernate built-in **dirty checking** mechanism.

**Comment by flybyray** [comment]
1. If `AUTO` was the default, it should stay the default.
   1. but note that the switch to `MANUAL` will not have to much influence to simple applications. It will change runtime behavior, like hibernate cache usage. It can speed up database (less querries).
1. But it should be(have to be) configurable in `application.conf` and documented, similar like `db.isolation`

I can just tell from a complex application for risk calculations, workflow and reporting engine (e.g. hibernate 'triggers' on changes). `AUTO` flush will run your application in situations where you do not want to auto flush triggering changes within calculations (therefore it must be configurable!!!). even on some db it will produce locks on database level, somehow it depends on the `db.isolation`, but most off the time applications use read_commited. i am not sure about it but i might remember some cases where some optimisticlock exceptions occured because of `AUTO` flush. We 'hacked' the entity-manager session to change that behavior in specific cases. But I think for a framework like Play! it should not be the solution for it.

Personally i really believe that `MANUAL` should be the right choice for the Play!-framework. [Transaction management](https://www.playframework.com/documentation/1.4.x/jpa#anametransactionsTransactionmanagementa)
> Play will automatically manage transactions for you. It will start a transaction for each HTTP request and commit it when the HTTP response is sent.

In combination with [Keep the model stateless](https://www.playframework.com/documentation/1.4.x/model#anamestatelessKeepthemodelstatelessa) an auto-flush in hibernate would introduce a break of this: 
> Play is designed to operate in a ‘share nothing’ architecture.

At all do not forget [Explicit save](https://www.playframework.com/documentation/1.4.x/jpa#anamesaveExplicitsavea)
> All the persistent objects extending the JPASupport/JPAModel will not be saved without an explicit call to the save() method.

> If your code throws an exception, the transaction will automatically rollback.

**Comment by asolntsev** [comment]
@flybyray I agree, it definitely should be configurable.
I am not sure about the default value. It can break existing applications. 

@xael-fry What do you think?

**Comment by flybyray** [comment]
created https://github.com/playframework/play1/pull/1139
Hibernate will use AUTO by default. You have to override with a setting in application.conf

**Pull request closed without merging**
