### PR TITLE
Add return type for Play.fatalServerError

### PR DESCRIPTION
**Pull request by Shredder121**
This allows reasoning about code path, and eliminates false positives with code analysis tools.

### CODE REVIEW

**Comment by xael-fry** [comment]
Can you create an issue about the problem in [lighthouse](https://play.lighthouseapp.com/projects/57987-play-framework/)

**Comment by Shredder121** [comment]
I just did that, it's ticket [#2012](https://play.lighthouseapp.com/projects/57987-play-framework/tickets/2012-codebase-improvements).

**Comment by Shredder121** [comment]
If there are any tickets about previous fixes (specifically things that have been proposed but not accepted) could you maybe mention that?
Then I won't reattempt that.

**Comment by Shredder121** [comment]
Hm, if you ever want to continue this, then ping me.

**Pull request closed without merging**
