### PR TITLE
Updated 3rd party dependencies

### PR DESCRIPTION
**Pull request by tazmaniax**
All tests pass locally (openjdk 21.0.1 2023-10-17 LTS).

### CODE REVIEW

**Comment by tazmaniax** [comment]
Looking at the JDK 11 run log it looks like there is a missing Python dependency `imp` in [cmdloader.py](https://github.com/tazmaniax/play1/blob/dependencies_update_20231113/framework/pym/play/cmdloader.py#L2). I can't see how the dependency update in this pull request could impact the Python dependencies.

```
     [echo] Testing development lifecycle (wait ...)
     [exec] 
     [exec] # --- Hello, I am a job-developer
     [exec] 
     [exec] 
     [exec] # --- Create a new project
     [exec] 
     [exec] RUN  ['/home/runner/work/play1/play1/samples-and-tests/i-am-a-developer/i-am-creating-jobs-here/../../../play', 'new', '/home/runner/work/play1/play1/samples-and-tests/i-am-a-developer/i-am-creating-jobs-here/jobapp', '--name=JOBAPP']
     [exec] RUNNING  1970
     [exec] Traceback (most recent call last):
     [exec]   File "/home/runner/work/play1/play1/samples-and-tests/i-am-a-developer/i-am-creating-jobs-here/../../../play", line 13, in <module>
     [exec]     from play.cmdloader import CommandLoader
     [exec]   File "/home/runner/work/play1/play1/framework/pym/play/cmdloader.py", line 2, in <module>
     [exec]     import imp
     [exec] ModuleNotFoundError: No module named 'imp'
     [exec] @@@@ TIMEOUT !
     [exec] kill play PID=1970
     [exec] Call http://localhost:9001/@kill
     [exec] play is KILLED with exception
     [exec] kill play PID=1970
     [exec] Call http://localhost:9001/@kill
     [exec] play is KILLED with exception
```

Here is the same run running locally on my machine
```
     [echo] Testing development lifecycle (wait ...)
     [exec]
     [exec] # --- Hello, I am a job-developer
     [exec]
     [exec]
     [exec] # --- Create a new project
     [exec]
     [exec] RUN  ['/Users/chris/git/PlanSocial/play1/samples-and-tests/i-am-a-developer/i-am-creating-jobs-here/../../../play', 'new', '/Users/chris/git/PlanSocial/play1/samples-and-tests/i-am-a-developer/i-am-creating-jobs-here/jobapp', '--name=JOBAPP']
     [exec] RUNNING  7954
     [exec] ~ Resolving dependencies using /Users/chris/git/PlanSocial/play1/samples-and-tests/i-am-a-developer/i-am-creating-jobs-here/jobapp/conf/dependencies.yml,
     [exec] ~
     [exec] ~
     [exec] ~ Installing resolved dependencies,
     [exec] ~
     [exec] ~ 	modules/docviewer -> /Users/chris/git/PlanSocial/play1/modules/docviewer
     [exec] ~
     [exec] ~ Done!
     [exec] ~
     [exec] ~        _            _
     [exec] ~  _ __ | | __ _ _  _| |
     [exec] ~ | '_ \| |/ _' | || |_|
     [exec] ~ |  __/|_|\____|\__ (_)
     [exec] ~ |_|            |__/
     [exec] ~
     [exec] ~ play! 1.7.x-1.7.1-73-g32e09c259, https://www.playframework.com
     [exec] ~
     [exec] ~ The new application will be created in /Users/chris/git/PlanSocial/play1/samples-and-tests/i-am-a-developer/i-am-creating-jobs-here/jobapp
     [exec] ~
     [exec] ~ OK, the application is created.
     [exec] ~ Start it with : play run /Users/chris/git/PlanSocial/play1/samples-and-tests/i-am-a-developer/i-am-creating-jobs-here/jobapp
     [exec] ~ Have fun!
     [exec]
     [exec] # --- Run the newly created job-application
     [exec]
     [exec] RUN  ['/Users/chris/git/PlanSocial/play1/samples-and-tests/i-am-a-developer/i-am-creating-jobs-here/../../../play', 'run', '/Users/chris/git/PlanSocial/play1/samples-and-tests/i-am-a-developer/i-am-creating-jobs-here/jobapp']
     [exec] RUNNING  7956
     [exec] OpenJDK 64-Bit Server VM warning: Options -Xverify:none and -noverify were deprecated in JDK 13 and will likely be removed in a future release.
     [exec] Listening for transport dt_socket at address: 8000
     [exec] Nov 15, 2023 9:16:06 AM play.Logger warn
     [exec] WARNING: auto configuration log4j2
     [exec] 09:16:06.740 [main] INFO  play - Starting /Users/chris/git/PlanSocial/play1/samples-and-tests/i-am-a-developer/i-am-creating-jobs-here/jobapp
     [exec] :: loading settings :: url = jar:file:/Users/chris/git/PlanSocial/play1/framework/lib/ivy-2.5.2.jar!/org/apache/ivy/core/settings/ivysettings.xml
     [exec] 09:16:06.851 [main] INFO  play - Module docviewer is available (/Users/chris/git/PlanSocial/play1/modules/docviewer)
     [exec] 09:16:07.162 [main] WARN  play - You're running Play! in DEV mode
     [exec] /Users/chris/.pyenv/versions/3.10.6/lib/python3.10/socket.py:776: ResourceWarning: unclosed <socket.socket fd=7, family=AddressFamily.AF_INET6, type=SocketKind.SOCK_STREAM, proto=6, laddr=('::1', 53976, 0, 0), raddr=('::1', 9001, 0, 0)>
     [exec]   self._sock = None
     [exec] ResourceWarning: Enable tracemalloc to get the object allocation traceback
     [exec] 09:16:07.190 [main] INFO  play - Listening for HTTP on port 9001 (Waiting a first request to start) ...
     [exec]
     [exec] # --- Send request to start app
     [exec]
     [exec]
     [exec] # --- check that job completed before processing request
```

**Comment by straycat264** [comment]
You're using Python 3.12 - the imp module's been removed. Unrelated issue -
for now, switch to Python <= 3.11 (I think there's a separate ticket for
this)

**Comment by tazmaniax** [comment]
@straycat264 right ok, I'm using Python 3.10.6 on my local machine which is why it works there but Python 3.12.0 is being used as part of the automated GitHub Action builds.  I wonder when that was updated.

CleanShot 2023-11-15 at 10 59 36@2x

**Comment by xabolcs** [comment]
> You're using Python 3.12 - the imp module's been removed. Unrelated issue -

Yup, there is #1457 for that.
It's sad that it breaks the CI :confused:

**Comment by tazmaniax** [comment]
I include the changes in #1460 in this pull request so either this or that pull request is merged

**Comment by tazmaniax** [comment]
@xael-fry this is good to go

**Pull request merged**
