### PR TITLE
[#1897] Add dynamic inline images to emails without first writing to disk

### PR DESCRIPTION
**Pull request by tazmaniax**

### CODE REVIEW

**Comment by tazmaniax** [comment]
sure, are there any instructions on how to do this?

**Comment by xael-fry** [comment]
No really, just add some example as we did for ```EmbeddedImage``` in samples-and-tests\just-test-cases\app\notifiers\Welcome.java

**Comment by tazmaniax** [comment]
@xael-fry Added example/test but build is failing and couldn't see from build log what's wrong

**Comment by xael-fry** [comment]
Your code doesn't compile with java7
``` log
Description	Resource	Path	Location	Type
Cannot refer to the non-final local variable data defined in an enclosing scope	Welcome.java	/Test cases/app/notifiers	line 102	Java Problem
```

**Comment by tazmaniax** [comment]
@xael-fry fixed for Java 7

**Comment by xael-fry** [comment]
Merged and pushed in master and 1.3.x.
Thanks

**Pull request merged**
