### PR TITLE
#5: Update to latest Eclipse JDT Core v3.23 to enable JDK 14 source

### PR DESCRIPTION
**Pull request by tazmaniax**
Task-Url: https://github.com/tazmaniax/play1/issues/5

# Helpful things

## Fixes

Updated the Eclipse JDT Core version along with other source compile libraries.

## Purpose

Allows code to compile to JDK 14 source level

## Background Context

This was being held up because the "[Faster Groovy Templates](https://github.com/tazmaniax/play-fastergt)" had a compile issue using Eclipse JDT Core > v18 but this has now been resolved, see references below

## References

- https://github.com/tazmaniax/play-fastergt/issues/1
- https://github.com/tazmaniax/gt-engine/pull/3

### CODE REVIEW

**Comment by tazmaniax** [comment]
@tomparle this is an updated pull request of your pull request https://github.com/playframework/play1/pull/1332 for issue https://github.com/playframework/play1/issues/1324

**Comment by tazmaniax** [comment]
I fixed the issue with the old Groovy jars lying around but the build still seems to be broken - not sure what the issue is

**Comment by tazmaniax** [comment]
@tomparle @asolntsev @xael-fry  finally a good result here! That was a bit painful.

So all good under JDK 1.8 but under JDK 15 I get a few failing tests (binding, invocationContext) and a few with errors (errors, routing), but I haven't had a chance to resolve them yet. I'm out of time on this so if anyone else can investigate that would be great! Not sure if that is a blocker with accepting this pull request.
CleanShot 2020-11-10 at 12 47 44

**Comment by tomparle** [comment]
@tazmaniax congratulations for your work ! 

The changes in the Groovy Template do not seem obvious, good job for having figured this out.
It seems that all tests passed now ?

**Review by xael-fry — COMMENTED** [review]
seems good to me

**Comment by xael-fry** [comment]
merged thanks @tazmaniax

**Comment by tazmaniax** [comment]
@xael-fry I see you've merged #1325 and #1332 in commits https://github.com/playframework/play1/commit/1056dbcb97706d74c6be8a923fed79922d43e98b and https://github.com/playframework/play1/commit/e7d8fcb01becec231f24e31fe0c84507c349c6cb respectively but in fact this pull request superseded both of those and the Travis build appears to be failing with those commits so you might want to revert them on master

CleanShot 2020-12-14 at 08 08 08

**Comment by tazmaniax** [comment]
@xael-fry ok looks like the build failure has been resolved so all good.

CleanShot 2020-12-14 at 08 18 49

**Comment by xael-fry** [comment]
@tazmaniax Yes I see  my mistake after, there was some conflict in merge, but I fix it.
Thanks

**Pull request merged**
