### PR TITLE
[#2089] dependencies upgrade:

### PR DESCRIPTION
**Pull request by dejan2609**
```
* com.h2database:h2 1.4.193 -->> 1.4.194
* joda-time 2.9.7 -- >> 2.9.9
* mysql:mysql-connector-java 5.1.40 -->> 5.1.41
* org.codehaus.groovy:groovy-all 2.4.7 -->> 2.4.10
```

Related ticket: [Upgrade dependencies](https://play.lighthouseapp.com/projects/57987-play-framework/tickets/2089-upgrade-dependencies)

### CODE REVIEW

**Comment by dejan2609** [comment]
Note: all check passed, I just changed commit message little bit and pushed same changes again.

**Comment by asolntsev** [comment]
@dejan2609 Thank you for the pull request! Sorry for the delay.
Could you h2 to 1.4.195 and groovy-all to 2.4.11?

**Comment by asolntsev** [comment]
@dejan2609 Please note that groovy-all is already upgraded to 2.4.11 in master branch.

**Comment by dejan2609** [comment]
@asolntsev let me upgrade h2 to 1.4.195

**Comment by dejan2609** [comment]
@asolntsev: done and rebased.

**Comment by asolntsev** [comment]
@dejan2609 Merged. Thank you!
PS. Why mysql-connector-java 5.1.41, not 6.0.6?

**Comment by dejan2609** [comment]
@asolntsev nice point, I will include that upgrade into my next PR (along with few other dependences).

**Comment by dejan2609** [comment]
@asolntsev just FYI: mysql-connector-java **_6.x_** line is still not fully baked (i.e. only milestones are released so far):
- http://insidemysql.com/mysql-connectorjava-6-0-6-m5-has-been-released
- https://lists.mysql.com/java/9400

**Comment by asolntsev** [comment]
@dejan2609 Clear. Ok, thank you for information.

**Comment by flybyray** [comment]
missing bouncy castle upgrade https://github.com/playframework/play1/pull/1146

**Pull request merged**
